### ISSUE TITLE
Error loop after automatic service restart.

### ISSUE THREAD

**Issue by LouDnl** [LouDnl/Youless-LS120#1]
Error loop after automatic service restart.
```bash
Oct  3 05:00:03 sblinux systemd[1]: Started Youless Energy service.
Oct  3 05:00:04 sblinux python3[1036515]: Traceback (most recent call last):
Oct  3 05:00:04 sblinux python3[1036515]:   File "/home/sb/scripts/youless/dash_allgraphs_live.py", line 249, in <module>
Oct  3 05:00:04 sblinux python3[1036515]:     main(default=True)
Oct  3 05:00:04 sblinux python3[1036515]:   File "/home/sb/scripts/youless/dash_allgraphs_live.py", line 200, in main
Oct  3 05:00:04 sblinux python3[1036515]:     db.main()  # update database always once on loading the file
Oct  3 05:00:04 sblinux python3[1036515]:   File "/home/sb/scripts/youless/LS120/db_auto_import.py", line 32, in main
Oct  3 05:00:04 sblinux python3[1036515]:     parse_data().parse_tenminutes(type, read_youless().read_ten_minutes(type))
Oct  3 05:00:04 sblinux python3[1036515]:   File "/home/sb/scripts/youless/LS120/read_youless.py", line 148, in read_ten_minutes
Oct  3 05:00:04 sblinux python3[1036515]:     data[self.date.date().strftime('%Y-%m-%d')][1].insert(0, {self.time: self.value})
Oct  3 05:00:04 sblinux python3[1036515]: KeyError: '2021-10-03'
Oct  3 05:00:05 sblinux systemd[1]: youless.service: Main process exited, code=exited, status=1/FAILURE
Oct  3 05:00:05 sblinux systemd[1]: youless.service: Failed with result 'exit-code'.
Oct  3 05:00:05 sblinux systemd[1]: youless.service: Consumed 1.050s CPU time.
Oct  3 05:00:06 sblinux systemd[1]: youless.service: Scheduled restart job, restart counter is at 2.
Oct  3 05:00:06 sblinux systemd[1]: Stopped Youless Energy service.
Oct  3 05:00:06 sblinux systemd[1]: youless.service: Consumed 1.050s CPU time.
```

**Comment by LouDnl** [comment]
> looks like this is because the database tables were not created.
